# fly.toml file generated for justwatch-done-right on 2023-02-12T19:49:50-03:00

app = "justwatch-done-right"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "8080"

[healthchecks]
  interval = "10s"
  timeout = "2s"
  http = "http://localhost:$PORT/healthcheck"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    soft_limit = 75
    hard_limit = 100
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 10 # after 10 consecutive failures, the vm will be restarted
    timeout = "2s"
